version: "3.8"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: asacCoupang
      MYSQL_PASSWORD: "rootroot"
      MYSQL_ROOT_PASSWORD: "rootroot"
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql

  docker_tutorial:
    build: .
    environment:
      SPRING_PROFILE: local
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
