version: "3"
services:
  mysql:
    container_name: mysql_host
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: asacCoupang
      MYSQL_PASSWORD: "rootroot"
      MYSQL_ROOT_PASSWORD: "rootroot"
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql

  docker_tutorial:
    build: .
    ports:
      - 8081:8080
    environment:
      SPRING_PROFILE: ${SPRING_PROFILE}
    depends_on:
      - mysql

volumes:
  mysql-data:
